### ISSUE TITLE
FEAT: add an option for "tail" cursors

### ISSUE THREAD

**Issue by JulienMaille** [SunsetTechuila/Cursor-Colors-Synchronizer#2]
Nice stuff! (and thanks for your PR on my spicetify theme)
Do you have any plans to add as an option the *tailed* version of the cursors from Jepri?
https://www.deviantart.com/jepricreations/art/Windows-11-Free-Tail-Cursor-Concept-962242647

![image](https://github.com/SunsetTechuila/Cursor-Colors-Synchronizer/assets/182520/7284672a-cd7c-477e-b2c2-f2e7caf0543b)

**Comment by SunsetTechuila** [comment]
will do

**Comment by SunsetTechuila** [comment]
@JulienMaille here you go

**Comment by JulienMaille** [comment]
Thanks a lot!
